# Generated by Django 4.1.2 on 2022-12-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_answer_date_alter_question_date_likeanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='mery.jpg', null=True, upload_to='avatars/%Y/%m/%d'),
        ),
    ]
