# Generated by Django 4.1.2 on 2022-12-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/common_avatar.png', null=True, upload_to='avatars/%Y/%m/%d'),
        ),
    ]
